import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'

import English_Auction from "../artifacts/contracts/English_Auction.sol/English_Auction.json";

import Web3 from 'web3'
import * as contract_end_point from '../contract_deployed_endpoint';
import {Eng_contract} from './Eng_Auction_contract.js';


export default function Eng_Auction() {
    const [contract, setContract] = useState(null);
    const [web3, setWeb3] = useState(null)
    const [address, setAddress] = useState(null)

    const connectToMetamask = async () => {
        alert("Connecting to metamask")
        /* To check if metamask is installed */
        if (typeof window !== "undefined" && typeof window.ethereum !== "undefined") {
            try {
              /* request wallet connect */
              await window.ethereum.request({ method: "eth_requestAccounts" })
              /* create web3 instance and set to state var */
              const web3 = new Web3(window.ethereum)
              /* set web3 instance */
              setWeb3(web3)
              /* get list of accounts */
              const accounts = await web3.eth.getAccounts()
              /* set Account 1 to React state var */
              setAddress(accounts[0])
              console.log("Accounts 0",+accounts[0])
    
              const vm = Eng_contract(web3)
              //vm.methods.getVendingMachineBalance().call().then(console.log);
              setContract(vm);
            } catch(err) {
              setError(err.message)
            }
        } else {
            // meta mask is not installed use ganache
            console.log("install MetaMask use ganache instead")
        }
      }

  return (
    <>
    <div>
  <Head>
    <title>Vending machine app</title>
    <meta name="description" content="Generated by create next app" />
  </Head>
</div>
    <div>
      <button> click me onClick={connectToMetamask} </button>
    </div>
    </>
  )
}
