import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="wrapper" style={{ 
      backgroundImage: `url('/eth_logo.jpg')`,  
      backgroundSize: 'cover',  backgroundRepeat:'no-repeat', height : "100vh" }}>
    <div className={styles.container}>
      <Head>
        <title>Dapp Bidding Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="d-inline-flex align-items-center text-white mt-3" >
          Welcome to Dapp Bidding project UI
        </h1>

      
      </main>
    </div>
    </div>
  )
}
